format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipUdp}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TCPIP_UDP_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipUdp, value: '16360'}
- type: ElementPosition
  attributes: {x: '21', y: '19', id: tcpipUdp}
