configName: sam_e70_xult
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: ATSAME70Q21B
projectName: ''
settings:
  PackageFilter: audio;azure_rtos;bsp;bt;core;crypto;cryptoauthlib;crypto_for_4.8.1;csp;csp_apps_sam_9x60;csp_apps_sam_a5d2;Devices;dev_packs;gfx;harmony-services;motor_control;net;net_apps_pic32mx;net_apps_pic32mz;net_apps_sam_9x60;net_apps_sam_a5d2;net_apps_sam_e5x;net_apps_sam_e70_v71;net_apps_sam_rh71;quick_docs;usb;wireless;wireless_wifi;zzz_expresslogic_threadx
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: OVERWRITE
  DFPPath: .\dev_packs\Microchip\SAME70_DFP\4.7.108\same70b\atdf\ATSAME70Q21B.atdf
