format_version: v1.0
type: UniqueComponent
attributes: {id: drvExtPhyKsz8091}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: DRV_ETHPHY_MAC_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvExtPhyKsz8091, value: GMAC}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: libdrvExtPhyKsz8091}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drvGmac}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: GMAC_PHY_Dependency}
- type: ElementPosition
  attributes: {x: '152', y: '72', id: drvExtPhyKsz8091}
