format_version: v1.0
type: UniqueComponent
attributes: {id: drvMiim}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: DRV_MIIM_RTOS_STACK_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '4096'}
- type: ElementPosition
  attributes: {x: '30', y: '60', id: drvMiim}
