format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipSnmp}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TCPIP_SNMP_CUSTOM_TEMPLATE_SL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipSnmp, value: 'false'}
  - type: Integer
    attributes: {id: TCPIP_SNMP_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipSnmp, value: '120'}
  - type: String
    attributes: {id: TCPIP_SNMP_MOUNT_POINT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: /mnt/mchpSite1/}
- type: ElementPosition
  attributes: {x: '170', y: '225', id: tcpipSnmp}
