format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipIPv6}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TCPIP_IPV6_ULA_GENERATE_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: TCPIP_IPV6_ULA_NTP_ACCESS_TMO}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: TCPIP_IPV6_ULA_NTP_VALID_WINDOW}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
- type: ElementPosition
  attributes: {x: '360', y: '161', id: tcpipIPv6}
