format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipHttp}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TCPIP_HTTP_CUSTOM_TEMPLATE_SL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipHttp, value: 'true'}
  - type: String
    attributes: {id: TCPIP_HTTP_FREE_FUNC}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: vPortFree}
  - type: Integer
    attributes: {id: TCPIP_HTTP_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipHttp, value: '1840'}
  - type: String
    attributes: {id: TCPIP_HTTP_MALLOC_FUNC}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: pvPortMalloc}
- type: ElementPosition
  attributes: {x: '170', y: '140', id: tcpipHttp}
