format_version: v1.0
type: UniqueComponent
attributes: {id: sys_fs}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: SYS_FS_FAT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: SYS_FS_MAX_FILES}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '25'}
- type: Attachments
  children:
  - type: MultiCapability
    attributes: {id: sys_fs_DRV_MEDIA_dependency}
    children:
    - type: TargetAttachments
      children:
      - type: TargetAttachment
        attributes: {targetComponentID: drv_sdmmc_0, targetAttachmentID: drv_media}
- type: ElementPosition
  attributes: {x: '332', y: '54', id: sys_fs}
