format_version: v1.0
type: UniqueComponent
attributes: {id: lib_wolfcrypt}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: cryptoCrya_03710}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_wolfcrypt, value: 'false'}
  - type: Boolean
    attributes: {id: cryptoCrya_U2803}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_wolfcrypt, value: 'false'}
  - type: Boolean
    attributes: {id: cryptoCrya_U2805}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_wolfcrypt, value: 'false'}
  - type: Boolean
    attributes: {id: wolfcrypt_aes_hw}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: wolfcrypt_random_hw}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: wolfcrypt_sha1_hw}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: wolfcrypt_sha224}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: wolfcrypt_sha264_hw}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: wolfssl_included}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: lib_wolfcrypt, value: 'true'}
- type: ElementPosition
  attributes: {x: '592', y: '248', id: lib_wolfcrypt}
