format_version: v1.0
type: GroupComponent
attributes: {displayName: TCP/IP STACK, id: TCP/IP STACK}
children:
- type: ElementPosition
  attributes: {x: '737', y: '77', id: TCP/IP STACK}
- type: Attachments
  children:
  - type: Attachment
    attributes: {targetComponentID: lib_wolfssl, namespace: PRESENTATION LAYER, id: 'net_Pres:Net_Pres_Crypto_Dependency',
      targetAttachmentID: lib_wolfssl}
