format_version: v1.0
type: UniqueComponent
attributes: {id: lib_wolfssl}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: wolfsslOsalHeapKeys}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: WolfSSL_Crypto_Dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: lib_wolfcrypt}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: lib_wolfcrypt}
- type: ElementPosition
  attributes: {x: '866', y: '314', id: lib_wolfssl}
