format_version: v1.0
type: UniqueComponent
attributes: {id: lib_wolfmqtt}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: WMQTT_CSTM_APP_TEMPLATE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: WMQTT_NET_GLUE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: WMQTT_NET_GLUE_DEBUG_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '900', y: '75', id: lib_wolfmqtt}
