format_version: v1.0
type: UniqueComponent
attributes: {id: drvGmac}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: DRV_INTMAC_PHY_TYPE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvGmac, value: KSZ8061}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: GMAC_PHY_Dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drvExtPhyKsz8061}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: libdrvExtPhyKsz8061}
  - type: DirectCapability
    attributes: {id: libdrvGmac}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: tcpipNetConfig_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: NETCONFIG_MAC_Dependency}
- type: ElementPosition
  attributes: {x: '180', y: '20', id: drvGmac}
