format_version: v1.0
configName: sam_e70_xult_freertos
folderName: sam_e70_xult_freertos
frameworkPath: C:\harmony\h3
processor: ATSAME70Q21B
projectName: sam_e70_xult_freertos
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAME70_DFP\4.10.248\same70b\atdf\ATSAME70Q21B.atdf
